# Problem 1: Choose Your Pokemon
    # For the following code call the function so that it prints
    # out the following to console:
def choose_pokemon(my_pokemon):
	for pokemon in my_pokemon:
		print(f"{pokemon} I choose you!")
		
my_pokemon = ["Pikachu", "Charizard", "Eevee"]
choose_pokemon(my_pokemon)

print("-------------------------------------------------------")
# problem 2: Rotate Left
    # Write a function rotate_left() that takes in 
    # a string s and an integer n and an integer n as parameters. 
	# The function reyurns a new string with the first n characters
	# moved to the end of the string where 1 <= n <= len(str)
'''
U:
    given a string s and an integer n as the stop position 
	where we will move the first letters of the string
P:
- Brainstorming: 
    Use stringindexing 

define a function with the appropiate parameters
for element in range(len(n)) # element is the index of the string
if element == n: 
    new_s = s[element + 1:] + s[:element]
return new_s
'''
# I: 
def rotate_left(s, n):
	for i in range(len(s)):
		if i == n:
			new_s = s[i:] + s[:i]
	return new_s

s = "rotation"
print(rotate_left(s, 2))
# What did you learn? String interpolation with indexing

print("-------------------------------------------------------")
# Problem 3: First Duplicate
    # Write a function first_repeated_char() that takes in a string s as a parameter and 
	# returns the index of the first repeated character in the string. 
	# Uppercases and lowercase letters are considered different characters,
	# and the function returns None if there are no repeated characters. 
'''
U:
Based on a string s return the index of the first repeated character in the string 
Return none if there are no repeated characters
P:
- brainstorm: 
    We will need a lot of loops here and I could possibly use a list but 
    with a list do you want to save the character of the index itself!?!

	define a function with the appropiate parameters 
	initialize a repetitions dictionary
	for character in s: 
	if s not in dictionary:
	add it and initialize to 1
	else: 
	add 1 
	
	for the first key in the dictionary: (I think here you have to use )
	
'''
# Example of ennumerates
s = "cat"
for thing in enumerate(s):
	print(thing)
print("----------------------------")

# Another example of enumerate
letters = ['a', 'b', 'c']

for letter in letters:
	print(letter)
'''
output: 
a
b
c
'''
print("----------------------------")

	# But what if you also want the position of the index
for i, letter in enumerate(letters, start = 1):
	print(i, letter)
'''
output: notice we start the indexing at 1
1 a
2 b
3 c
'''
print("----------------------------")
	# But what if we want normal indexing and not to start at index 1
letters = ['a', 'b', 'c']
for i, letter in enumerate(letters): # for the index of the letter and the value itself 
	print(i, letter)
'''
output: notice we start with normal indexing
0 a
1 b
2 c
'''
print("----------------------------")
	# What if we dont do enumerates and we do normal coding
for i in range(len(letters)):
	print(i, letters[i])
'''
output:
0 a
1 b
2 c
'''
print("--------------------------------------------------------")
'''

'''
def first_repeated_char(s):
	seen = {} # initialize a dictionary of the seen characters in 
	
	# we usually do for char in s, 
	# this time we want the character and its index!
	for i, char in enumerate(s): # get the index and the variable of string s
		
		if char in seen: 
			return i
		else:
			seen[char] = i

s = "hello world"
s2 = "aAbBCC"
s3 = "abcdefg"

print(first_repeated_char(s))
print(first_repeated_char(s2))
print(first_repeated_char(s3))

print("--------------------------------------------------------")
# Problem 4: Find Impostor
	# Write a function find_difference() that takes two strigs as parameters.
	# The second string is generated by shuffling the first string 
	# and adding one more letter at a random position. 
	# Search for and return the added letter.
'''
U:
for a function that takes two strings find the added letter from the first string to the second
P:
define a function with the appropiate parameters
for char in s2:
if char not in s1:
return char
'''
# I:
def find_difference(s1, s2):
	for char in s2:
		if char not in s1:
			return char
	
s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))

print("--------------------------------------------------------")
# Problem 5: Longest Substring
	# Write a function that takes in a string s and return the length 
	# of the longest substring without repeating characters. 
'''
U:
find the longest stretch without repeating characters
P:
- Brainstorm:
	I need some sort of while loop, for what I am not sure...

define a function and parameter s, as the string
for character in string s
while character is not repeating 
	How do I make it so that the current char is not equal to the previous char 
	char - 1
'''
# I: 
def length_of_longest_substring(s):
	
	no_repeats_list = [] # initialize an epty list to store the longest without repeat, 
	# then count this out in the following loop

	for index in range(len(s)): # char is the index 
		while 0 < index < len(s): # while the index is greater than 0 but less than len(s) ... 
			if s[index] != s[index - 1]: # if the current character at the index is not equal to the previous one 
				no_repeats_list.append() # append it to the no repeating list
		
	# counting the amount of characters in the list s2
	count_list = 0
	for  letter in no_repeats_list: # for a letter in the no repeating list
		count_list += 1 # for every letter in the list we add 1 (to count )
	return count_list # should return a number
		
s = "abcdeefghhhhh"
count = length_of_longest_substring(s)
print(count)

s2 = "aaaaaaaaaaaaaaa"
count = length_of_longest_substring(s2)
print(count)

# Problem 6: Roman to integer
	# Roman numberals are represented by seven different symnols (I, V, X, L, C, D, and M)
	# and have these unique corresponding values: 
		# I = 1 V = 5
		# X = 10 L = 50
		# C = 100 D = 500
		# M = 1000
	# Example 1: 2 -> II (I + I)
	# Example 2: 12 -> XII (x + II)
	# Example 3: 27 -> XXVII (XX + V + II)

	# Example 4: 4 -> IV (I - V) 
	# Example 5: 9 -> IX (I - X)
		# if the number is in front and it is smaller 
		# than the second, then it means we substract it
'''
U:
write a function roman_to_int() that takes in a string s 
that makes up a roman numberal. 
The function should return the value of s.
- Brainstorm: for each time we get a roman numberal representation
we should return an integer
asume each time we can add the before symbol to the next 
unless the one before is less than the one after 

make sure you account for the three cases as shown 

P:
define a function with the appropiate parameters
initiate all variables as roman numberals with the appropiate equators as the integers
for 
if curren character less than character before it  
'''
def roman_to_int(s):
	values_dictionary = { 'I': 1, 'V': 5, 'X': 10,'L': 50, 'C': 100, 'D': 500, 'M': 1000}
	for i in range(len(s)):
		
			
